## NumPyとは

```
NumPyとは、Pythonのサードパーティ製のパッケージであり、配列や行列を効率よく扱うことができます。
NumPyには配列を扱うためのndarrayと、行列を扱うためのmatrixという型があり、これらの型で要素を扱う場合はintやfloatなど、特定のデータ型に揃える必要があります。
また、NumPyには関数やメソッドや用意されており、これらを利用することで高速に配列や行列の計算を行うことができます。
```



In [ ]:
import numpy as np

In [ ]:
# 配列をndarray型で定義
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
# 型
type(a)

numpy.ndarray

In [ ]:
# データ構造
a.shape

(3,)

In [ ]:
# 次元数
a.ndim

1

In [ ]:
# 2次元配列をndarry型で定義
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 構造
b.shape

(2, 3)

In [ ]:
# インデックス指定で取得
b[1, 0]

4

In [ ]:
# スライス
a[1:]

array([2, 3])

In [ ]:
# 置き換え
b[:, 2] = 8
b 

array([[1, 2, 8],
       [4, 5, 8]])

In [ ]:
# 合計,a.sum()でも同様
np.sum(a)

6

In [ ]:
# データ型
a.dtype

dtype('int64')

In [ ]:
# 明示的に型指定
c = np.array([1,2,3], dtype=np.int16)
c

array([1, 2, 3], dtype=int16)

In [ ]:
# 型変換
# c自体は更新されないことに注意
c.astype(np.float16)

array([1., 2., 3.], dtype=float16)

In [ ]:
# 次元変換
# 変換する際に、要素数が足りない場合や割り切れない場合はエラー（ValueError）
c1 = np.array([1, 2, 3, 4, 5, 6])
c2 = c1.reshape(2,3)
c2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2次元を1次元へ変換
# ravelメソッドが参照元を返すのに対し、flattenメソッドはコピーを返す。
# =,copyと同様
c4 = c2.ravel()
c4

array([1, 2, 3, 4, 5, 6])

In [ ]:
#　数列から配列生成
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
# random
# seedで乱数固定
np.random.seed(123)
f_array = np.random.random((4,2))
f_array

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [ ]:
## 整数。小数はuniform。標準正規分布はrandn。
np.random.randint(1, 10, (3, 5))

array([[1, 1, 4, 5, 1],
       [1, 5, 2, 8, 4],
       [3, 5, 8, 3, 5]])

In [ ]:
# 0行列
np.zeros(3)

array([0., 0., 0.])

In [ ]:
# 1行列
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# full関数を使って、整数10を5つ持つ配列を定義
np.full((2, 3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [ ]:
# 指定した範囲の値を等間隔で区切った要素からなる配列
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# 要素間の差分
l = np.array([1,4,-2,2,10])
np.diff(l)

array([ 3, -6,  4,  8])

In [ ]:
# 結合
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a,b],axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20], [30, 40]])
np.concatenate([c, d], axis=1)

array([[ 1,  2,  3, 10, 20],
       [ 4,  5,  6, 30, 40]])

In [ ]:
# 2次元配列の列分割:
a = np.array([[1, 2, 10], [3, 4, 20], [5, 6, 30], [7, 8, 40]])
col1, col2 = np.hsplit(a, [2])
col1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
col2

array([[10],
       [20],
       [30],
       [40]])

In [ ]:
# 転置
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# newaxisは要素数を指定する必要なし
a = np.array([1, 2, 3])
a[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# グリッドデータの生成
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])
xx, yy = np.meshgrid(x, y)
xx

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# ユニバーサルファンクション:配列内の要素に対して一括で処理を行う機能
# a = np.array([[-1, -2, -3, 4, 5], [6, 7, -8, -9, -10]])
np.abs(a)

array([1, 2, 3])

In [ ]:
# ブロードキャスト:配列内の要素に対して直接演算などの処理を行うための機能
a = np.array([1, 2, 3])
d = np.array([[1], [2], [3]])
a + d
d.shape

(3, 1)

In [ ]:
# infを計算結果に含ませない
a = np.array([1, 2, 3])
a_inf = np.array([0, 2, 0])
a / (a_inf+1e-6)

array([1.000000e+06, 9.999995e-01, 3.000000e+06])

In [ ]:
# 内積 @でも可
a = np.array([1, 2, 3])
b = np.array([[-1, -2, -3], [4, 5, 6]])
np.dot(b, a)

array([-14,  32])

In [ ]:
# 判定
a = np.array([[-1, -2], [3, 4], [5, 6]])
a > 0

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
# 条件を満たす要素数
np.count_nonzero(a > 0)

4

In [ ]:
np.sum(a > 3)

3

In [ ]:
# 条件を満たす要素が存在するか
np.any(a >= 5)

True

In [ ]:
# すべての要素が条件を満たしているか
np.all(a > 0)

False

In [ ]:
# 条件を満たす要素の取得
a[a > 3]

array([4, 5, 6])

In [ ]:
# 配列同士の比較
a = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([1, 2, 3])
a == c

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
# 同じ構成か。誤差+-10。
np.allclose(a, b, atol=10)

False